### PR TITLE
doc: fix logrus link

### PR DESCRIPTION
**Pull request by tomsquest**

### CODE REVIEW

**Comment by morningvera** [comment]
I'm running into a couple snags with our CI (haven't dealt with PRs from forks yet). Working on a fix and then I'll merge this PR.

**Comment by morningvera** [comment]
Hey @tomsquest, this is good to merge. Thanks again!

**Comment by sum2000** [comment]
> Hey @tomsquest, this is good to merge. Thanks again!

In order to preserve your signature, we request you to squash and merge. Please use the default commit message provided by the Github UI.

**Comment by tomsquest** [comment]
Rebased PR.

**Comment by morningvera** [comment]
Hi @tomsquest, this could've been merged by simply pressing the "squash and merge" button. But since you've done this now, can you please rebase against rotisserie/master and squash this to one commit. Thanks!

**Comment by tomsquest** [comment]
Hi @morningvera , there is no "squash and merge` button on my side (fork side). I am far from being an expert in Git and Github plumbing.
So basically is see your merge _in_ my branch, which I do not seem able to squash into my commit (that why I tried to rebase, ie. to pick my commit and put it on top).

Any instruction is welcome, else this PR is a bit of a shame, so do as you wish.

**Comment by sum2000** [comment]
@tomsquest Thanks for your contribution! Cheers

**Comment by tomsquest** [comment]
Thanks for merging it!

**Pull request merged**
